---
kafka:
    tcb:
        address: 192.168.40.21:9092
        topic:
            name: tcb-topic
        group:
            id: tcb-import

# logging
logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    level:
        org:
            springframework:
                web: INFO
            hibernate: ERROR
        guru:
            springframework:
                blogs:
                    controllers: INFO

spring:
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          zkNodes: localhost:9092,127.0.0.1:9092
          brokers: localhost:2181,127.0.01:2181
